/**
 * Nigeria country profile.
 */
import type { CountryProfile } from "./index.ts";

export const profile: CountryProfile = {
  code: "ng",
  name: "Nigeria",
  currency: "NGN",
  subunitMultiplier: 100,
  subunitLabel: "kobo",
  timezone: "Africa/Lagos",

  identifierSystems: [
    {
      system: "https://nimc.gov.ng/nin",
      label: "National Identification Number",
      docType: "NIN",
    },
    {
      system: "https://nibss-plc.com.ng/bvn",
      label: "Bank Verification Number",
      docType: "BVN",
    },
  ],

  benefitCodes: [
    { code: "1", display: "Medical Care" },
    { code: "2", display: "Surgical" },
    { code: "3", display: "Consultation" },
    { code: "4", display: "Diagnostic X-Ray" },
    { code: "5", display: "Diagnostic Lab" },
    { code: "6", display: "Renal Dialysis" },
    { code: "8", display: "Prospective Payment" },
    { code: "11", display: "Optical (Eye Exams)" },
    { code: "14", display: "Renal Supplies" },
    { code: "23", display: "Diagnostic Dental" },
    { code: "24", display: "Periodontics" },
    { code: "25", display: "Restorative Dental" },
    { code: "26", display: "Endodontics" },
    { code: "27", display: "Maxillofacial Prosthetics" },
    { code: "28", display: "Adjunctive Dental Services" },
    { code: "30", display: "Health Benefit Plan Coverage" },
    { code: "35", display: "Dental Care" },
    { code: "36", display: "Dental Crowns" },
    { code: "37", display: "Dental Accident" },
    { code: "45", display: "Hospice" },
    { code: "47", display: "Hospital" },
    { code: "48", display: "Intermediate Care Facility" },
    { code: "50", display: "Outpatient" },
    { code: "54", display: "Long Term Care Pharmacy" },
    { code: "55", display: "Skilled Nursing Facility" },
    { code: "56", display: "Medically Related Transportation" },
    { code: "61", display: "In-vitro Fertilization" },
    { code: "62", display: "MRI/CAT Scan" },
    { code: "63", display: "Donor Procedures" },
    { code: "69", display: "Maternity" },
    { code: "76", display: "Level of Care 1" },
    { code: "77", display: "Level of Care 2" },
    { code: "78", display: "Level of Care 3" },
    { code: "79", display: "Level of Care 4" },
    { code: "80", display: "Level of Care 5" },
    { code: "81", display: "Level of Care 6" },
    { code: "82", display: "Level of Care 7" },
    { code: "83", display: "Level of Care 8" },
    { code: "84", display: "Level of Care 9" },
    { code: "85", display: "Level of Care 10" },
    { code: "86", display: "Level of Care 11" },
    { code: "87", display: "Level of Care 12" },
    { code: "88", display: "Level of Care 13" },
    { code: "89", display: "Level of Care 14" },
    { code: "90", display: "Level of Care 15" },
    { code: "91", display: "Level of Care 16" },
    { code: "92", display: "Level of Care 17" },
    { code: "93", display: "Level of Care 18" },
    { code: "94", display: "Level of Care 19" },
    { code: "95", display: "Level of Care 20" },
    { code: "F1", display: "Medical Coverage" },
    { code: "F3", display: "Dental Coverage" },
    { code: "F4", display: "Hearing Coverage" },
    { code: "F6", display: "Vision Coverage" },
  ],
};
